version: "3.9"
services:
  fastapi:
    build:
      context: .
    ports:
      - 8000:80
    volumes:
      - ./:/usr/app/
    env_file:
      - ./.env
    environment:
      - TOKEN_EXPIRE=10
    command: --reload
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=fastapi
    volumes:
    - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: always

